runtime: python37

# [START handlers]
handlers:
- url: /.*
  script: auto

- url: /index.html
  script: /Templates/index.html

- url: /index2.html
  script: /Templates/index2.html

- url: /Templates
  static_dir: Templates

# [END handlers]
