runtime: python37

# [START handlers]
handlers:
- url: /.*
  script: main.py

- url: /index.html
  static_files: Templates/index.html
  upload: Templates/index.html

- url: /Templates
  static_dir: Templates


# [END handlers]
