runtime: python37

# [START handlers]
handlers:
- url: /.*
  script: auto

- url: /Templates/index.html
  static_files: Templates/index.html
  upload: Templates/index.html

- url: /Templates
  static_dir: Templates
  upload: Templates

# [END handlers]
