runtime: python37

# [START handlers]
handlers:
- url: /.*
  script: auto

- url: /.*
  static_files: /Templates/

- url: /Templates
  static_dir: /Templates/
  upload: Templates/.*\.(gif|png|jpg)$

# [END handlers]
